
const info = [{src:"boissy", 
               text:"École de la source\nBoissy-L'Aillerie, Francia",
               info:{title:"Ecole de Boissy",
                     headers: ["7 Rue Macaigne Fortier, Boissy-l'Aillerie, France",
                               "En curso"],
                     paragraphs: ["COLABORACIÓN: CMD ARQUITECTURA",
                                  "Misión de Estudios Preliminares y Fase Conceptual para el proyecto de extensión de una escuela primaria y secundaria de 356 alumnos a 192 alumnos.",
                                  "Terreno: 400M2\nConstrucción interior total: 1400M2",
                                  "Cliente: A.E.C."],
                     images: ["boissy1",
                              "boissy2",
                              "boissy3",
                              "boissy4",
                              "boissy5",
                              "boissy6",
                              "boissy7",
                              "boissy8",
                              "boissy9",
                              "boissy10",
                              "boissy11",
                              "boissy12"]

               }},
              {src:"casa30", 
               text:"Casa 142.5",
               info:{title:"Casa 142.5",
                     headers: ["Av. Toluca, Ciudad de México",
                               "2016- En Construcción"],
                     paragraphs: ["Proyecto de casa habitacional, diseñada exclusivamente para una mujer soltera. La única petición de nuestro cliente es su ubicación a 142.5 grados cómo símbolo de soberanía.",
                                  "Materiales: Concreto celular, cal, micro-cemento, madera Guanacastle, piedra volcánica, metal.",
                                  "Terreno: 210m2",
                                  "Construcción: 110m2",
                                  "Cliente: Privado"],
                     images: ["casa301",
                              "casa302",
                              "casa303",
                              "casa304",
                              "casa305",
                              "casa306",
                              "casa307",
                              "casa308",
                              "casa309",
                              "casa3010",
                              "casa3011",
                              "casa3012"]

               }},
              {src:"castillo", text:"Castillo"},
              {src:"colodion", text:"Colodion num.13"},
              {src:"espita", text:"Espita"},
              {src:"herkles", text:"Héraklês"},
              {src:"hualemna", text:"Hualemna"},
              {src:"instrucciones", text:"Instrucciones\npara un arquitecto"},
              {src:"invisible", text:"Invisible\nInvencible"},
              {src:"kancaba", text:"Hacienda\nKancaba"},
              {src:"laredocion", text:"Laredo 18"},
              {src:"lilianeicon", text:"Li-Liane"},
              {src:"losciclos", text:"El ciclo\nde la piel"},
              {src:"mataicon", text:"Mata\nRestaurante"},
              {src:"mazatlanicon", text:"Mazatlan 70"},
              {src:"media", text:"Media de puntos"},
              {src:"mipiedr", text:"Mi piedra\nMi Camino"},
              {src:"myrte", text:"Casa Myrte"},
              {src:"num5", text:"Casa num.5"},
              {src:"onor", text:"Onora"},
              {src:"paisajesonoro", text:"Paisaje(s)\nSonoro(s)"},
              {src:"pdm", text:"Poema dual en\nmultifrecuencia"},
              {src:"plan", text:"Plan de escape"},
              {src:"sema", text:"Sema"},
              {src:"senal", text:"Señal\nvideo mapping"},
              {src:"senderos", text:"Senderos\ndocumental"},
              {src:"tension", text:"Tensión\nsuperficial"},
              {src:"xucu", text:"Hacienda Xucú"},];





export default {
                 info };