
const info = [{src:"boissy", 
               text:"École de la source\nBoissy-L'Aillerie, Francia",
               info:{title:"Ecole de Boissy",
                     headers: ["7 Rue Macaigne Fortier, Boissy-l'Aillerie, France",
                               "En curso"],
                     paragraphs: ["COLABORACIÓN: CMD ARQUITECTURA",
                                  "Misión de Estudios Preliminares y Fase Conceptual para el proyecto de extensión de una escuela primaria y secundaria de 356 alumnos a 192 alumnos.",
                                  "Terreno: 400M2\nConstrucción interior total: 1400M2",
                                  "Cliente: A.E.C."],
                     images: ["boissy1",
                              "boissy2",
                              "boissy3",
                              "boissy4",
                              "boissy5",
                              "boissy6",
                              "boissy7",
                              "boissy8",
                              "boissy9",
                              "boissy10",
                              "boissy11",
                              "boissy12"]
               }},
              {src:"casa30", 
               text:"Casa 142.5",
               info:{title:"Casa 142.5",
                     headers: ["Av. Toluca, Ciudad de México",
                               "2016- En Construcción"],
                     paragraphs: ["Proyecto de casa habitacional, diseñada exclusivamente para una mujer soltera. La única petición de nuestro cliente es su ubicación a 142.5 grados cómo símbolo de soberanía.",
                                  "Materiales: Concreto celular, cal, micro-cemento, madera Guanacastle, piedra volcánica, metal.",
                                  "Terreno: 210m2",
                                  "Construcción: 110m2",
                                  "Cliente: Privado"],
                     images: ["casa301",
                              "casa302",
                              "casa303",
                              "casa304",
                              "casa305",
                              "casa306",
                              "casa307",
                              "casa308",
                              "casa309",
                              "casa3010",
                              "casa3011",
                              "casa3012"]

               }},
              {src:"castillo", 
               text:"castillo",
               info:{title:"El Castillo de Barba Azul",
                     headers: ["Escenografía para la ópera escrita por Bela Bartok",
                               "2016"],
                     paragraphs: ["Diseño de escenografía basada en la composición triangular del compositor hungaro Bela Bartok.",
                                  "Materiales:Madera, metal, fieltro, espejo, vinil.",
                                  "Medidas: Variables",
                                  "Cliente: Ópera anónima"],
                     images:["castillo1",
                             "castillo2",
                             "castillo3",
                             "castillo4",
                             "castillo5",
                             "castillo6",
                             "castillo7",
                             "castillo8",
                             "castillo9",
                             "castillo10",
                             "castillo11"]}
              },
              {src:"colodion", 
               text:"Colodion",
               info:{title:" Colodión Num.13",
                     headers: ["Álbum Fotográfico en Metales Blandos",
                               "2013 / Finalizado"],
                     paragraphs: ["La re-interpretación del segundo proceso comercial de la historia de fotografía (Colodión humedo) cómo anécdota a materiales de nuestra industria actual.",
                                  "Materiales: Aluminio, Cobre, Latón, Piezografía, Papel entintando, Caoba.",
                                  "Dimensiones: Variables",
                                  "Cliente: Trabajo Personal"],
                     images:["colodion1",
                             "colodion2",
                             "colodion3",
                             "colodion4",
                             "colodion5",
                             "colodion6",
                             "colodion7",
                             "colodion8",
                             "colodion9"]}},
              {src:"espita", 
               text:"Espita",
               info:{title:"Espita casa",
                     headers: ["Espita, Yucatán, México",
                               "2014"],
                     paragraphs: ["Colaboración: Arq. Raúl Hernández",
                                  "Materiales: Piedra caliza, cal, mosaico de pasta, concreto blanco, metal.",
                                  "Maderas: Chacté, Tzalam, Bejuco.",
                                  "Terreno:: 150m2 construida ",
                                  "Remodelación:150m2",
                                  "Construcción nueva: 15m2",
                                  "Cliente: Presidente Municipal Espita"],
                     images:["espita01",
                             "espita02",
                             "espita03",
                             "espita04",
                             "espita05",
                             "espita06",
                             "espita07",
                             "espita08",
                             "espita09",
                             "espita10",
                             "espita11",
                             "espita12",
                             "espita13",
                             "espita14",
                             "espita15"]}},
              {src:"herakles", 
               text:"Héraklês",
               info:{title:"Héraklês",
                     headers: ["Diseño de Tres Baldosas",
                               "2015 / Entregado"],
                     paragraphs: ["Diseño de tres baldosas en cemento pigmentado, y con grabado en láser para apliación en muros.",
                                  "Materiales: Cemento, Pigmentos, Grabado láser.",
                                  "Dimensiones: 20cm2",
                                  "Peso: 120gr",
                                  "Cliente: Privado"],
                     images:["herakles01",
                             "herakles02",
                             "herakles03",
                             "herakles04",
                             "herakles05",
                             "herakles06",
                             "herakles07"]}},
              {src:"hualemnah", 
               text:"Hualemnah",
               info:{title:"Hua Lem Nah - Centro de Salud",
                     headers: ["Diseño de Tres Baldosas",
                               "2015 / Entregado"],
                     paragraphs: ["El centro de salud 'Hualemnah' fue comisionado por el grupo 'Fuente del corazón' con la intención principal de tener un centro de estudios para la medicina alternativa con la doble función de residencias para estadías de más de tres meses.",
                                  "Materiales :Cemento, madera: Tzalam-Habim, paja, metal, téxtil.",
                                  "Iluminación: Bombillas incandecentes.",
                                  "Área Total : 1073 m2",
                                  "Construcción: 600m2 (10 Cabañas de 25m2, Restaurante 100m2, Talleres 250m2)",
                                  "Cliente:FUENTE DEL CORAZON SA DE CV"],
                     images:["hualemnah01",
                             "hualemnah02",
                             "hualemnah03",
                             "hualemnah04",
                             "hualemnah05",
                             "hualemnah06",
                             "hualemnah07",
                             "hualemnah08",
                             "hualemnah09",
                             "hualemnah10",
                             "hualemnah11",
                             "hualemnah12",
                             "hualemnah13",
                             "hualemnah14",
                             "hualemnah15"]}},
              {src:"instrucciones", 
               text:"Instrucciones\npara un arquitecto",
               info:{title:"Instrucciones para un Arquitecto",
                     headers: ["Serie Fotográfica",
                               "2013 / Finalizado"],
                     paragraphs: ["El cabinete de curiosidades de una casa de finales del siglo XIX que sufrió su demolición en el año 2013.",
                                  "Materiales: Fotografía en impresión cromógena.",
                                  "Dimensiones: 52 x 70cm",
                                  "Cliente: Trabajo Personal"],
                     images:["instrucciones01",
                             "instrucciones02",
                             "instrucciones03",
                             "instrucciones04",
                             "instrucciones05",
                             "instrucciones06",
                             "instrucciones07"]}},
              {src:"invisible", 
               text:"Invisible\nInvencible",
               info:{title:"Invencible / Invisible",
                     headers: ["Serie Fotográfica",
                               "2014 / Finalizado"],
                     paragraphs: ["Serie fotográfica de ocho objetos que revelan su campo electromagnético gracias a una técnica de la física electrónica re-titulada: Obturación electroestática.",
                                  "Materiales: Fotografía en impresión cromógena.",
                                  "Dimensiones: 52 x 70cm",
                                  "Cliente: Trabajo Personal"],
                     images:["instrucciones01",
                             "instrucciones02",
                             "instrucciones03",
                             "instrucciones04",
                             "instrucciones05",
                             "instrucciones06",
                             "instrucciones07"]}},
              {src:"kancaba", text:"Hacienda\nKancaba"},
              {src:"laredocion", text:"Laredo 18"},
              {src:"lilianeicon", text:"Li-Liane"},
              {src:"losciclos", text:"El ciclo\nde la piel"},
              {src:"mataicon", text:"Mata\nRestaurante"},
              {src:"mazatlanicon", text:"Mazatlan 70"},
              {src:"media", text:"Media de puntos"},
              {src:"mipiedr", text:"Mi piedra\nMi Camino"},
              {src:"myrte", text:"Casa Myrte"},
              {src:"num5", text:"Casa num.5"},
              {src:"onor", text:"Onora"},
              {src:"paisajesonoro", text:"Paisaje(s)\nSonoro(s)"},
              {src:"pdm", text:"Poema dual en\nmultifrecuencia"},
              {src:"plan", text:"Plan de escape"},
              {src:"sema", text:"Sema"},
              {src:"senal", text:"Señal\nvideo mapping"},
              {src:"senderos", text:"Senderos\ndocumental"},
              {src:"tension", text:"Tensión\nsuperficial"},
              {src:"xucu", text:"Hacienda Xucú"},];





export default {
                 info };